config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'

  devise_for :admins
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations',
               passwords: 'users/passwords'
             }

  # Admin constraint for Sidekiq Web UI
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users, only: %i[index show]

  resources :activities do
    resources :bookings, only: %i[create destroy]
  end
  resources :bookings, only: %i[index show]

  post '/logs/create', to: 'logs#create'
  root 'activities#index'
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  acts_as_paranoid
  has_many :logs
  belongs_to :user
  belongs_to :activity

  validates :booker_name, presence: true
  validates :booker_email, format: { with: URI::MailTo::EMAIL_REGEXP, message: 'E-Mail格式輸入錯誤' }, presence: true
  validates :user_id, uniqueness: { scope: :activity_id, message: '你已經參加了！' }

  scope :booking, -> { where(deleted_at: nil) }
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

class BookingsController < ApplicationController
  before_action :authenticate_user!

  def create
    ActiveRecord::Base.transaction do
      @activity = Activity.find(params[:activity_id])
      if has_space?(@activity) && open_for_booking?(@activity)
        @booking = @activity.bookings.new(booking_params.merge(user: current_user))
        raise ActiveRecord::Rollback, '請確實填寫資料' unless @booking.save

        current_user.logs.create!(type: 'submitted', booking: @booking, activity: @activity)
        redirect_to @activity, notice: '報名成功'
      else
        redirect_to root_path, alert: '人數已滿或者時間已經超過了'
        raise ActiveRecord::Rollback
      end
    end
  rescue ActiveRecord::Rollback => e
    redirect_to @activity, alert: e.message.presence || '無法完成報名'
  end

  def destroy
    @booking = current_user&.bookings&.find(params[:id])
    @booking.destroy
    current_user.logs.create!(type: 'cancel_booking', booking: @booking)
    redirect_to bookings_path, notice: '報名已經取消'
  end

  def index
    @bookings = current_user&.bookings&.includes(:activity)
  end

  def show
    @booking = current_user&.bookings&.find(params[:id])
    current_user.logs.create!(type: 'browse_booked_show', booking: @booking)
  rescue ActiveRecord::RecordInvalid
    Rails.logger.error "browse booking show page log create failed, user id : #{current_user.id}"
  end

  private

  def booking_params
    params.require(:booking).permit(:booker_name, :booker_email, :activity_id).merge(user: current_user)
  end
end

app/helpers/booking_helper.rb
# frozen_string_literal: true

module BookingHelper
end

app/views/bookings/_form.html.erb
<% unless current_user&.already_booked?(@activity) %>
  <%= form_with model: [activity, booking], data: { turbo: false } do |f| %>
    <%= f.hidden_field :activity_id, value: @activity.id %>
    <div>
      <%= f.label :booker_name, '報名者姓名：' %>
      <%= f.text_field :booker_name, placeholder: '請輸入姓名' %>
    </div>
    <div>
      <%= f.label :booker_email, '報名者信箱' %>
      <%= f.email_field :booker_email, placeholder: '請輸入Email', 
                          data: { 
                            controller: "email-tracking",
                            action: "input->email-tracking#trackEmailInput",
                            email_tracking_target: "email",
                            email_tracking_activity_id_value: @activity.id } %>
    </div>
    <%= f.submit '參加活動' %>
  <% end %>
<% end %>

app/views/bookings/index.html.erb
<h1>已報名的活動</h1>
<% if current_user.bookings.exists? %>
  <% current_user.bookings.each do |booking| %>
    <% if booking.activity.present? %>
      <%= link_to booking_path(booking) do %>
        <h2>活動標題：<%= booking.activity.title %></h2>
        <p>活動簡介：<%= booking.activity.description %></p>
        <div>活動時間：<%= booking.activity.start_time %></div>
        <div>活動地點：<%= booking.activity.location %></div>
      <% end %>
    <% else %>
      <p>某些預訂的活動未找到或已被刪除。</p>
    <% end %>
  <% end %>
<% else %>
  <p>沒有找到已預訂的活動。</p>
<% end %>

app/views/bookings/show.html.erb
<h1>報名資訊</h1>
<div>
  <%= link_to '取消報名', activity_booking_path(@booking), data: { turbo_method: 'delete',
                                                                 turbo_confirm: '確定要取消報名嗎？' } %>
</div>
<%= render 'shared/activity_info', resources: @booking.activity %>