config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'

  devise_for :admins
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations',
               passwords: 'users/passwords'
             }

  # Admin constraint for Sidekiq Web UI
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users, only: %i[index show]

  resources :activities do
    resources :bookings, only: %i[create destroy]
  end
  resources :bookings, only: %i[index show]

  post '/logs/create', to: 'logs#create'
  root 'activities#index'
end

app/views/shared/_activity_info.html.erb
<article>
  <h2>活動主題：<%= resources.title %></h2>
  <h3>主辦單位：<%= resources.organizer %></h3>
  <p>主辦人：<%= resources.user.name %></p>
  <h4>活動地點：<%= resources.location %></h4>
  <div>報名人數：<%= resources.bookings.count %> / <%= resources.max_participants %></div>
  <div>開始時間：<%= format_datetime(resources.start_time) %> 至  <%= format_datetime(resources.end_time) %></div>
  <p>詳細內容：<%= resources.description %></p>
</article>

app/views/shared/_errors_message.html.erb
<% if form.errors.any? %>
  <div id='error_explanation'>
    <h2 class="text-red-500 font-bold text-xl"><%= pluralize(form.errors.count, 'error') %>必需填寫:</h2>
    <ul>
    <% form.errors.full_messages.each do |message| %>
      <li class=" text-lg text-red-500"><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% [:notice, :alert].each do |type| %>
  <% if flash[type] %>
    <div class="<%= type %> text-center mt-[20px]">
      <%= flash[type] %>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="flex items-center">
  <% if user_signed_in? %>
    <div class="px-2 mx-2 flex justify-end">
      <h3><span class='text-sm font-bold hover:text-green-700'><%= "#{current_user.name} (#{current_user.email})" %></span></h3>
    </div>
  <% end %>
  <%= link_to '學習王', root_path, class: "px-2 mx-2 text-3xl font-bold hover:text-green-700" %>
  <% if user_signed_in? %>
    <div class="px-2 mx-2">
      <%= link_to '登出', destroy_user_session_path, data: { turbo_method: "delete" }, class: 'text-3xl font-bold hover:text-red-700' %>
    </div>
    <div class="px-2 mx-2">
      <%= link_to '更改密碼', edit_user_registration_path, class:'text-3xl font-bold hover:text-green-700' %>
    </div>
    <div class="px-2 mx-2">
      <%= link_to '建立活動', new_activity_path, class:'text-3xl font-bold hover:text-green-700' %>
    </div>
    <div class="px-2 mx-2">
      <%= link_to '我參加的活動', bookings_path, class:'text-3xl font-bold hover:text-green-700' %>
    </div>
    <div class="px-2 mx-2">
      <%= link_to '追蹤使用者', users_path, class:'text-3xl font-bold hover:text-green-700' %>
    </div>
  <% else %>
    <div class="px-2 mx-2">
      <%= link_to '註冊 / 登入', new_user_session_path, class: 'text-3xl font-bold hover:text-green-700', data: { controller: "login" } %>
    </div>
  <% end %>
</nav>