config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'

  devise_for :admins
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations',
               passwords: 'users/passwords'
             }

  # Admin constraint for Sidekiq Web UI
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users, only: %i[index show]

  resources :activities do
    resources :bookings, only: %i[create destroy]
  end
  resources :bookings, only: %i[index show]

  post '/logs/create', to: 'logs#create'
  root 'activities#index'
end

app/models/activity.rb
# frozen_string_literal: true

class Activity < ApplicationRecord
  acts_as_paranoid
  belongs_to :user
  has_many :bookings
  has_many :logs

  validates :title, :description, :start_time, :end_time, :location, :organizer, presence: true
  validates :max_participants, presence: true, numericality: { greater_than: 5, only_integer: true }
  validate :end_time_greater_than_start_time

  private

  def end_time_greater_than_start_time
    return if end_time.blank? || start_time.blank?
    return unless end_time <= start_time

    errors.add(:end_time, '必須晚於開始時間')
  end
end

app/controllers/activities_controller.rb
# frozen_string_literal: true

class ActivitiesController < ApplicationController
  before_action :find_activity, only: %i[show edit update destroy]

  def new
    @activity = Activity.new
    authorize @activity
  end

  def create
    @activity = Activity.new(activity_params)
    authorize @activity
    if @activity.save
      redirect_to activities_path, notice: '活動建立成功'
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
    current_user&.logs&.create!(type: 'browse_activity_show', activity: @activity)
  rescue ActiveRecord::RecordInvalid
    Rails.logger.error "browse activity booking page log create failed, user id : #{current_user.id}"
  end

  def edit
    authorize @activity
  end

  def update
    authorize @activity
    if @activity.update(activity_params)
      redirect_to activity_path(@activity), notice: '活動更新成功'
    else
      render :edit
    end
  end

  def destroy
    authorize @activity
    @activity.destroy
    redirect_to activities_path, notice: '活動已經刪除'
  end

  def index
    @activities = Activity.all
    current_user&.logs&.create!(type: 'browse_root')
  rescue ActiveRecord::RecordInvalid
    Rails.logger.error "browse root page log create failed, user id : #{current_user.id}"
  end

  private

  def find_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:title, :description, :start_time, :end_time, :location, :organizer, :status,
                                     :max_participants).merge(user: current_user)
  end
end

app/helpers/activities_helper.rb
# frozen_string_literal: true

module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= render 'shared/errors_message', form: form %>
<div>
  <%= form_with(model: form, lacal: true, data: { turbo: false }) do |f| %>
    <div>
      <%= f.label :title, '活動標題' %>
      <%= f.text_field :title, placeholder: '請填寫活動標題' %>
    </div>

    <div>
      <%= f.label :description, '活動介紹' %>
      <%= f.text_area :description, placeholder: '請填寫活動內容' %>
    </div>

    <div>
      <%= f.label :start_time, '活動開始時間' %>
      <%= f.datetime_local_field :start_time %>
    </div>

    <div>
      <%= f.label :end_time, '活動結束時間' %>
      <%= f.datetime_local_field :end_time %>
    </div>

    <div>
      <%= f.label :location, '活動地點' %>
      <%= f.text_field :location, placeholder: '請填寫活動地點' %>
    </div>

    <div>
      <%= f.label :max_participants, '人數限制' %>
      <%= f.number_field :max_participants, placeholder: '請填寫人數' %>
    </div>

    <div>
      <%= f.label :organizer, '活動單位' %>
      <%= f.text_field :organizer, placeholder: '請填寫活動單位' %>
    </div>

    <div>
      <%= f.submit %>
    </div>

  <% end %>
</div>

app/views/activities/edit.html.erb
<h1>編輯活動</h1>
<%= render 'form', form: @activity %>

app/views/activities/index.html.erb
<h1>活動一覽</h1>
<article>
  <% @activities.each do |activity| %>
    <%= link_to activity_path(activity) do %>
      <h2>活動標題：<%=  activity.title %></h2>
      <p>活動簡介：<%= activity.description %></p>
      <div>活動時間：<%= activity.start_time %></div>
      <div>活動地點：<%= activity.location %></div>
    <% end %>
  <% end %>
</article>

app/views/activities/new.html.erb
<h1>建立活動</h1>
<%= render 'form', form: @activity %>

app/views/activities/show.html.erb
<h1>活動資訊</h1>
<% if policy(@activity).edit?  %>
  <div>
    <%= link_to '修改活動內容', edit_activity_path(@activity) %>
  </div>
<% end %>
<% if policy(@activity).destroy? %>
  <div>
    <%= link_to '刪除活動',activity_path(@activity), data: { turbo_method: 'delete', turbo_confirm: '確定要刪除嗎？'  } %>
  </div>
<% end %>
<%= render 'shared/activity_info', resources: @activity %>
<div>
  <%= render 'bookings/form', booking: @booking, activity: @activity %>
</div>